[workspace]
members = [
    "bindings/*",
    "crates/*",
]
default-members = [
    "crates/*",
]
resolver = "2"

[workspace.package]
homepage = "https://github.com/TBD54566975/web5-rs"
repository = "https://github.com/TBD54566975/web5-rs.git"
license-file = "LICENSE"

[workspace.dependencies]
thiserror = "1.0.50"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
serde_with = "3.4.0"
uniffi = { version = "0.27.0" }
