[workspace]
members = [
    "crates/*",
]
default-members = [
    "crates/*",
]
resolver = "2"

[workspace.package]
homepage = "https://github.com/TBD54566975/web5-rs"
repository = "https://github.com/TBD54566975/web5-rs.git"
license-file = "LICENSE"

[workspace.dependencies]
thiserror = "1.0.50"
serde = { version = "1.0.193", features = ["derive"] }
sha2 = "0.10.8"
