

// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!



#include <stdbool.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
	// We also try to prevent mixing versions of shared uniffi header structs.
	// If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V6
	#ifndef UNIFFI_SHARED_HEADER_V6
		#error Combining helper code from multiple versions of uniffi is not supported
	#endif // ndef UNIFFI_SHARED_HEADER_V6
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V6
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V6 in this file.           ⚠️

typedef struct RustBuffer {
	int32_t capacity;
	int32_t len;
	uint8_t *data;
} RustBuffer;

typedef int32_t (*ForeignCallback)(uint64_t, int32_t, uint8_t *, int32_t, RustBuffer *);

// Task defined in Rust that Go executes
typedef void (*RustTaskCallback)(const void *, int8_t);

// Callback to execute Rust tasks using a Go routine
//
// Args:
//   executor: ForeignExecutor lowered into a uint64_t value
//   delay: Delay in MS
//   task: RustTaskCallback to call
//   task_data: data to pass the task callback
typedef int8_t (*ForeignExecutorCallback)(uint64_t, uint32_t, RustTaskCallback, void *);

typedef struct ForeignBytes {
	int32_t len;
	const uint8_t *data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
	int8_t code;
	RustBuffer errorBuf;
} RustCallStatus;

// Continuation callback for UniFFI Futures
typedef void (*RustFutureContinuation)(void * , int8_t);

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V6 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H

// Needed because we can't execute the callback directly from go.
void cgo_rust_task_callback_bridge_web5(RustTaskCallback, const void *, int8_t);

int8_t uniffiForeignExecutorCallbackweb5(uint64_t, uint32_t, RustTaskCallback, void*);

void uniffiFutureContinuationCallbackweb5(void*, int8_t);

void uniffi_web5_uniffi_fn_free_bearerdid(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_web5_uniffi_fn_constructor_bearerdid_from_portable_did(
	void* portable_did,
	RustCallStatus* out_status
);

void* uniffi_web5_uniffi_fn_constructor_bearerdid_new(
	RustBuffer uri,
	void* key_manager,
	RustCallStatus* out_status
);

RustBuffer uniffi_web5_uniffi_fn_method_bearerdid_get_data(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_web5_uniffi_fn_method_bearerdid_get_signer(
	void* ptr,
	RustBuffer key_id,
	RustCallStatus* out_status
);

void uniffi_web5_uniffi_fn_free_did(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_web5_uniffi_fn_constructor_did_new(
	RustBuffer uri,
	RustCallStatus* out_status
);

RustBuffer uniffi_web5_uniffi_fn_method_did_get_data(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_web5_uniffi_fn_free_diddht(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_web5_uniffi_fn_constructor_diddht_from_identity_key(
	RustBuffer identity_key,
	RustCallStatus* out_status
);

void* uniffi_web5_uniffi_fn_constructor_diddht_from_uri(
	RustBuffer uri,
	RustCallStatus* out_status
);

void uniffi_web5_uniffi_fn_method_diddht_deactivate(
	void* ptr,
	void* signer,
	RustCallStatus* out_status
);

RustBuffer uniffi_web5_uniffi_fn_method_diddht_get_data(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_web5_uniffi_fn_method_diddht_publish(
	void* ptr,
	void* signer,
	RustCallStatus* out_status
);

void uniffi_web5_uniffi_fn_free_didjwk(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_web5_uniffi_fn_constructor_didjwk_from_public_jwk(
	RustBuffer public_jwk,
	RustCallStatus* out_status
);

void* uniffi_web5_uniffi_fn_constructor_didjwk_from_uri(
	RustBuffer uri,
	RustCallStatus* out_status
);

RustBuffer uniffi_web5_uniffi_fn_method_didjwk_get_data(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_web5_uniffi_fn_free_document(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_web5_uniffi_fn_constructor_document_new(
	RustBuffer data,
	RustCallStatus* out_status
);

RustBuffer uniffi_web5_uniffi_fn_method_document_find_public_key_jwk(
	void* ptr,
	RustBuffer key_id,
	RustCallStatus* out_status
);

RustBuffer uniffi_web5_uniffi_fn_method_document_get_data(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_web5_uniffi_fn_free_ed25519signer(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_web5_uniffi_fn_constructor_ed25519signer_new(
	RustBuffer private_key,
	RustCallStatus* out_status
);

RustBuffer uniffi_web5_uniffi_fn_method_ed25519signer_sign(
	void* ptr,
	RustBuffer payload,
	RustCallStatus* out_status
);

void uniffi_web5_uniffi_fn_free_ed25519verifier(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_web5_uniffi_fn_constructor_ed25519verifier_new(
	RustBuffer public_jwk,
	RustCallStatus* out_status
);

int8_t uniffi_web5_uniffi_fn_method_ed25519verifier_verify(
	void* ptr,
	RustBuffer message,
	RustBuffer signature,
	RustCallStatus* out_status
);

void uniffi_web5_uniffi_fn_free_inmemorykeymanager(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_web5_uniffi_fn_constructor_inmemorykeymanager_new(
	RustCallStatus* out_status
);

void* uniffi_web5_uniffi_fn_method_inmemorykeymanager_get_as_key_manager(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_web5_uniffi_fn_method_inmemorykeymanager_get_signer(
	void* ptr,
	RustBuffer public_jwk,
	RustCallStatus* out_status
);

RustBuffer uniffi_web5_uniffi_fn_method_inmemorykeymanager_import_private_jwk(
	void* ptr,
	RustBuffer private_key,
	RustCallStatus* out_status
);

void uniffi_web5_uniffi_fn_free_keymanager(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_web5_uniffi_fn_method_keymanager_get_signer(
	void* ptr,
	RustBuffer public_jwk,
	RustCallStatus* out_status
);

void uniffi_web5_uniffi_fn_free_portabledid(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_web5_uniffi_fn_constructor_portabledid_new(
	RustBuffer json,
	RustCallStatus* out_status
);

RustBuffer uniffi_web5_uniffi_fn_method_portabledid_get_data(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_web5_uniffi_fn_free_presentationdefinition(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_web5_uniffi_fn_constructor_presentationdefinition_new(
	RustBuffer json_serialized_presentation_definition,
	RustCallStatus* out_status
);

RustBuffer uniffi_web5_uniffi_fn_method_presentationdefinition_get_json_serialized_presentation_definition(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_web5_uniffi_fn_method_presentationdefinition_select_credentials(
	void* ptr,
	RustBuffer vc_jwts,
	RustCallStatus* out_status
);

void uniffi_web5_uniffi_fn_free_resolutionresult(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_web5_uniffi_fn_constructor_resolutionresult_new(
	RustBuffer uri,
	RustCallStatus* out_status
);

RustBuffer uniffi_web5_uniffi_fn_method_resolutionresult_get_data(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_web5_uniffi_fn_free_signer(
	void* ptr,
	RustCallStatus* out_status
);

RustBuffer uniffi_web5_uniffi_fn_method_signer_sign(
	void* ptr,
	RustBuffer payload,
	RustCallStatus* out_status
);

void uniffi_web5_uniffi_fn_free_verifiablecredential(
	void* ptr,
	RustCallStatus* out_status
);

void* uniffi_web5_uniffi_fn_constructor_verifiablecredential_create(
	RustBuffer json_serialized_issuer,
	RustBuffer json_serialized_credential_subject,
	RustBuffer options,
	RustCallStatus* out_status
);

RustBuffer uniffi_web5_uniffi_fn_method_verifiablecredential_get_data(
	void* ptr,
	RustCallStatus* out_status
);

void uniffi_web5_uniffi_fn_free_verifier(
	void* ptr,
	RustCallStatus* out_status
);

int8_t uniffi_web5_uniffi_fn_method_verifier_verify(
	void* ptr,
	RustBuffer message,
	RustBuffer signature,
	RustCallStatus* out_status
);

void* uniffi_web5_uniffi_fn_func_did_dht_resolve(
	RustBuffer uri,
	RustCallStatus* out_status
);

void* uniffi_web5_uniffi_fn_func_did_jwk_resolve(
	RustBuffer uri,
	RustCallStatus* out_status
);

RustBuffer uniffi_web5_uniffi_fn_func_ed25519_generator_generate(
	RustCallStatus* out_status
);

RustBuffer ffi_web5_uniffi_rustbuffer_alloc(
	int32_t size,
	RustCallStatus* out_status
);

RustBuffer ffi_web5_uniffi_rustbuffer_from_bytes(
	ForeignBytes bytes,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rustbuffer_free(
	RustBuffer buf,
	RustCallStatus* out_status
);

RustBuffer ffi_web5_uniffi_rustbuffer_reserve(
	RustBuffer buf,
	int32_t additional,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_continuation_callback_set(
	RustFutureContinuation callback,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_poll_u8(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_cancel_u8(
	void* handle,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_free_u8(
	void* handle,
	RustCallStatus* out_status
);

uint8_t ffi_web5_uniffi_rust_future_complete_u8(
	void* handle,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_poll_i8(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_cancel_i8(
	void* handle,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_free_i8(
	void* handle,
	RustCallStatus* out_status
);

int8_t ffi_web5_uniffi_rust_future_complete_i8(
	void* handle,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_poll_u16(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_cancel_u16(
	void* handle,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_free_u16(
	void* handle,
	RustCallStatus* out_status
);

uint16_t ffi_web5_uniffi_rust_future_complete_u16(
	void* handle,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_poll_i16(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_cancel_i16(
	void* handle,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_free_i16(
	void* handle,
	RustCallStatus* out_status
);

int16_t ffi_web5_uniffi_rust_future_complete_i16(
	void* handle,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_poll_u32(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_cancel_u32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_free_u32(
	void* handle,
	RustCallStatus* out_status
);

uint32_t ffi_web5_uniffi_rust_future_complete_u32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_poll_i32(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_cancel_i32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_free_i32(
	void* handle,
	RustCallStatus* out_status
);

int32_t ffi_web5_uniffi_rust_future_complete_i32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_poll_u64(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_cancel_u64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_free_u64(
	void* handle,
	RustCallStatus* out_status
);

uint64_t ffi_web5_uniffi_rust_future_complete_u64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_poll_i64(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_cancel_i64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_free_i64(
	void* handle,
	RustCallStatus* out_status
);

int64_t ffi_web5_uniffi_rust_future_complete_i64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_poll_f32(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_cancel_f32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_free_f32(
	void* handle,
	RustCallStatus* out_status
);

float ffi_web5_uniffi_rust_future_complete_f32(
	void* handle,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_poll_f64(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_cancel_f64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_free_f64(
	void* handle,
	RustCallStatus* out_status
);

double ffi_web5_uniffi_rust_future_complete_f64(
	void* handle,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_poll_pointer(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_cancel_pointer(
	void* handle,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_free_pointer(
	void* handle,
	RustCallStatus* out_status
);

void* ffi_web5_uniffi_rust_future_complete_pointer(
	void* handle,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_poll_rust_buffer(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_cancel_rust_buffer(
	void* handle,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_free_rust_buffer(
	void* handle,
	RustCallStatus* out_status
);

RustBuffer ffi_web5_uniffi_rust_future_complete_rust_buffer(
	void* handle,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_poll_void(
	void* handle,
	void* uniffi_callback,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_cancel_void(
	void* handle,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_free_void(
	void* handle,
	RustCallStatus* out_status
);

void ffi_web5_uniffi_rust_future_complete_void(
	void* handle,
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_func_did_dht_resolve(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_func_did_jwk_resolve(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_func_ed25519_generator_generate(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_method_bearerdid_get_data(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_method_bearerdid_get_signer(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_method_did_get_data(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_method_diddht_deactivate(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_method_diddht_get_data(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_method_diddht_publish(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_method_didjwk_get_data(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_method_document_find_public_key_jwk(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_method_document_get_data(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_method_ed25519signer_sign(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_method_ed25519verifier_verify(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_method_inmemorykeymanager_get_as_key_manager(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_method_inmemorykeymanager_get_signer(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_method_inmemorykeymanager_import_private_jwk(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_method_keymanager_get_signer(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_method_portabledid_get_data(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_method_presentationdefinition_get_json_serialized_presentation_definition(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_method_presentationdefinition_select_credentials(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_method_resolutionresult_get_data(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_method_signer_sign(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_method_verifiablecredential_get_data(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_method_verifier_verify(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_constructor_bearerdid_from_portable_did(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_constructor_bearerdid_new(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_constructor_did_new(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_constructor_diddht_from_identity_key(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_constructor_diddht_from_uri(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_constructor_didjwk_from_public_jwk(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_constructor_didjwk_from_uri(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_constructor_document_new(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_constructor_ed25519signer_new(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_constructor_ed25519verifier_new(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_constructor_inmemorykeymanager_new(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_constructor_portabledid_new(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_constructor_presentationdefinition_new(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_constructor_resolutionresult_new(
	RustCallStatus* out_status
);

uint16_t uniffi_web5_uniffi_checksum_constructor_verifiablecredential_create(
	RustCallStatus* out_status
);

uint32_t ffi_web5_uniffi_uniffi_contract_version(
	RustCallStatus* out_status
);



