[package]
name = "web5-uniffi"
version = "0.1.0"
edition = "2021"
homepage.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
jwk = { path = "../../crates/jwk" }
uniffi = { git = "https://github.com/mozilla/uniffi-rs", rev = "7cd3aac735e905e1725d350a7a82d57aa50caaa1", features = ["cli"] }

[build-dependencies]
uniffi = { git = "https://github.com/mozilla/uniffi-rs", rev = "7cd3aac735e905e1725d350a7a82d57aa50caaa1", features = ["build"] }

[lib]
crate-type = ["cdylib"]
name = "web5"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"