[package]
name = "credentials"
version = "0.1.0"
edition = "2021"
homepage.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
jsonschema = "0.17.1"
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }

[dev-dependencies]
serde_canonical_json = "1.0.0"