#!/bin/bash

set -e

REPO_DIR=../../../../

rustup target add x86_64-pc-windows-msvc

(
  cd $REPO_DIR;
  cargo build --target x86_64-pc-windows-msvc --release --package web5_uniffi;
  mkdir -p bound/kt/src/main/resources;
  cp target/x86_64-pc-windows-msvc/release/web5_uniffi.dll \
    bound/kt/src/main/resources/libweb5_uniffi_x86_64_pc_windows_msvc.dll
)
