[package]
name = "dids"
version = "0.1.0"
edition = "2021"
homepage.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
async-trait = "0.1.74"
base64 = "0.22.0"
crypto = { path = "../crypto" }
did-web = "0.2.2"
multibase = "0.9.1"
regex = "1.10.4"
serde = { workspace = true }
serde_json = { workspace = true }
ssi-core = "0.1.0"
ssi-dids = "0.1.1"
thiserror = { workspace = true }

[dev-dependencies]
tokio = { version = "1.34.0", features = ["macros", "test-util"] }