[package]
name = "jwk"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
uniffi = { workspace = true }
sha2 = "0.10.8"
base64 = "0.22.0"

[lib]
crate-type = ["cdylib"]
name = "jwk"