#!/bin/bash 

set -e

REPO_DIR=../../../../

rustup target add aarch64-apple-darwin

(
  cd $REPO_DIR;
  cargo build --target aarch64-apple-darwin --release --package web5_uniffi;
  cp target/aarch64-apple-darwin/release/libweb5_uniffi.dylib \
    bound/kt/src/main/resources/libweb5_uniffi_aarch64_apple_darwin.dylib
)