name: Build CLI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_aarch64_apple_darwin:
    runs-on: macos-latest
    name: Build aarch64-apple-darwin target
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust 1.74.0
        run: rustup toolchain install 1.74.0
      - name: Set Rust 1.74.0 as default
        run: rustup default 1.74.0
      - name: Run Build Script
        run: |
          cd crates/web5_cli/build/aarch64_apple_darwin
          ./build
      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: web5-aarch64-apple-darwin
          path: target/aarch64-apple-darwin/release/web5_cli

  build_x86_64_apple_darwin:
    runs-on: macos-12
    name: Build x86_64-apple-darwin target
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust 1.74.0
        run: rustup toolchain install 1.74.0
      - name: Set Rust 1.74.0 as default
        run: rustup default 1.74.0
      - name: Run Build Script
        run: |
          cd crates/web5_cli/build/x86_64_apple_darwin
          ./build
      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: web5-x86_64-apple-darwin
          path: target/x86_64-apple-darwin/release/web5_cli

  build_x86_64_unknown_linux_gnu:
    runs-on: ubuntu-latest
    name: Build x86_64-unknown-linux-gnu target
    steps:
      - uses: actions/checkout@v2
      - name: Run Build Script
        run: |
          cd crates/web5_cli/build/x86_64_unknown_linux_gnu
          ./build
      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: web5-x86_64-linux-gnu
          path: target/x86_64-unknown-linux-gnu/release/web5_cli

  build_x86_64_unknown_linux_musl:
    runs-on: ubuntu-latest
    name: Build x86_64-unknown-linux-musl target
    steps:
      - uses: actions/checkout@v2
      - name: Run Build Script
        run: |
          cd crates/web5_cli/build/x86_64_unknown_linux_musl
          ./build
      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: web5-x86_64-linux-musl
          path: target/x86_64-unknown-linux-musl/release/web5_cli

  build_x86_64_pc_windows_msvc:
    runs-on: windows-latest
    name: Build x86_64-pc-windows-msvc target
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust 1.74.0
        run: rustup toolchain install 1.74.0
      - name: Set Rust 1.74.0 as default
        run: rustup default 1.74.0
      - name: Add MSVC target
        run: rustup target add x86_64-pc-windows-msvc
      - name: Build executable
        run: cargo build --target x86_64-pc-windows-msvc --release --package web5_cli
      - name: Upload executable
        uses: actions/upload-artifact@v4.0.0
        with:
          name: web5-x86_64-pc-windows-msvc
          path: target/x86_64-pc-windows-msvc/release/web5_cli
